- name: Wait for Netmaker API server to respond using curl
  command: >
    curl -s -o /dev/null -w "%{http_code}" -H "Authorization: Bearer {{ netmaker_master_key }}" 
    https://api.{{ netmaker_base_domain }}/api/networks
  register: _result
  until: _result.stdout == "200"
  retries: 30
  delay: 10

- name: Render createadminuser.json to /tmp 
  template:
    src: createadminuser.json.j2
    dest: /tmp/createadminuser.json

- name: Check if createadminuser.json exists
  stat:
    path: /tmp/createadminuser.json
  register: file_info

- name: Debug file info
  debug:
    var: file_info

- name: Add admin user using curl
  command: >
    curl -s -o /dev/null -w "%{http_code}"
    -X POST
    -H "Content-Type: application/json"
    -H "Authorization: Bearer {{ netmaker_master_key }}"
    -d @/tmp/createadminuser.json
    https://api.{{ netmaker_base_domain }}/api/users/{{ netmaker_admin_username }}
  register: _result
  failed_when: _result.stdout not in ["200", "400", "500"]

- name: Get all existing networks
  command: >
    curl -X GET
    -H 'Content-Type: application/json'
    -H 'Authorization: Bearer {{ netmaker_master_key }}'
    "https://api.{{ netmaker_base_domain }}/api/networks"
  register: existing_netmaker_networks
  until: existing_netmaker_networks.rc == 0

- name: Compose the new network list
  set_fact:
    new_netmaker_networks: "{{ ( new_netmaker_networks | list ) + ( [ {\"network_name\": item.network_name, \"node_keys\": item.node_keys, \"network_cidr\": item.network_cidr }] | list ) }}"
  when: ( existing_netmaker_networks.stdout | from_json ) | selectattr('netid', 'equalto', item.network_name) | list | count == 0
  with_items: "{{ netmaker_networks }}"
  

- name: Create new networks in netmaker
  command: >
    curl -X POST
    -H 'Content-Type: application/json'
    -H 'Authorization: Bearer {{ netmaker_master_key }}'
    -d "{{ lookup('template', 'createnetwork.json.j2') }}"
    "https://api.{{ netmaker_base_domain }}/api/networks"
  register: create_network_output
  until: create_network_output.rc == 0
  loop: "{{ new_netmaker_networks }}"

- name: Get keys
  command: >
    curl -X GET
    -H 'Content-Type: application/json'
    -H 'Authorization: Bearer {{ netmaker_master_key }}'
    "https://api.{{ netmaker_base_domain }}/api/v1/enrollment-keys"
  register: key_response
  until: key_response.rc == 0

- name: Add key for control network for netclient
  command: >
    curl -X POST
    -H 'Content-Type: application/json'
    -H 'Authorization: Bearer {{ netmaker_master_key }}'
    -d "{{ lookup('template', 'createkey.json.j2') }}"
    "https://api.{{ netmaker_base_domain }}/api/v1/enrollment-keys"
  register: add_key_response
  until: add_key_response.rc == 0 or ('400' in add_key_response.stdout and 'already exists' in add_key_response.stdout)
  vars:
    keytag: "{{ item.0.network_name }}-{{ item.1 }}"
  when: "( key_response.stdout | from_json ) | selectattr('tags', 'equalto', [keytag]) | list | count == 0"
  loop: "{{ new_netmaker_networks | subelements('node_keys') }}"

- name: Get keys again
  command: >
    curl -X GET
    -H 'Content-Type: application/json'
    -H 'Authorization: Bearer {{ netmaker_master_key }}'
    "https://api.{{ netmaker_base_domain }}/api/v1/enrollment-keys"
  register: key_response2
  until: key_response2.rc == 0

- name: copy keys
  copy: 
    content: "{{ key_response2.stdout }}"
    dest: "{{ netmaker_enrollment_key_list_file_location }}"
  delegate_to: localhost

# - name: Save access token for bastion netclient
#   vars:
#     query: "[?tags[0]=='{{ netmaker_control_network_name }}-access'].token"
#   set_fact:
#     netmaker_control_network_access_string: "{{ key_response2.json | json_query(query) | first }}"