- name: Install netclient gpgkey
  ansible.builtin.command: >
    wget -q --show-progress https://apt.netmaker.org/gpg.key -O /etc/apt/trusted.gpg.d/netclient.asc
  args:
    creates: /etc/apt/trusted.gpg.d/netclient.asc
  changed_when: false

- name: Set permissions on gpgkey
  ansible.builtin.file:
    path: /etc/apt/trusted.gpg.d/netclient.asc
    mode: 0777

- name: Install netclient package repo
  ansible.builtin.command: >
    wget -q https://apt.netmaker.org/debian.deb.txt -O /etc/apt/sources.list.d/netclient.list
  args:
    creates: /etc/apt/sources.list.d/netclient.list
  changed_when: false
  notify: Set repo permissions

- name: Set repo permissions
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/netclient.list
    mode: 0777

- name: Update apt cache
  shell: apt update

- name: Install dependencies
  package:
    name:
      - wireguard
      - netclient={{ netmaker_image_version }}-0
    state: present

- name: Load enrollment key file into a fact
  set_fact:
    netmaker_enrollment_keys: "{{ lookup('file', netmaker_enrollment_key_list_file_location) | from_json }}"

- name: Debug loaded enrollment keys and their type
  debug:
    msg:
      - "Type: {{ netmaker_enrollment_keys | type_debug }}"
      - "Value: {{ netmaker_enrollment_keys }}"

- name: Set token from enrollment keys
  vars:
    query: "[?tags[0]=='{{ item }}'].token"
  set_fact:
    netmaker_join_tokens: "{{ netmaker_join_tokens + [netmaker_enrollment_keys | json_query(query) | first] }}"
  when: not netmaker_join_tokens
  loop: "{{ netclient_enrollment_keys }}"

- name: Stop playbook execution immediately - Debug
  meta: end_play

- name: join netmaker network
  command: "netclient join -t {{ item }}"
  loop: "{{ netmaker_join_tokens }}"

- name: Ensure Netmaker client configuration directory exists
  file:
    path: /etc/netclient
    state: directory
    mode: '0755'

- name: Update Netmaker client configuration with inbound IP
  lineinfile:
    path: /etc/netclient/netclient.yml
    regexp: '^endpointip:'
    line: "endpointip: {{ ansible_host }}"
    create: yes
    state: present

- name: iptable accept on forward
  iptables:
    chain: FORWARD
    policy: ACCEPT

- name: "set netclient to auto restart"
  systemd:
    enabled: true
    daemon_reload: true
    name: "netclient"
    state: started
    force: true